<a href="https://colab.research.google.com/github/singhpriti5/Tf-Idf/blob/main/tf_idf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task 1

In [ ]:
from collections import Counter
from tqdm import tqdm
from scipy.sparse import csr_matrix
import math
import operator
from sklearn.preprocessing import normalize
import numpy
from math import log10

In [ ]:
import pickle
with open('cleaned_strings', 'rb') as f:
    corpus = pickle.load(f)
# printing the length of the corpus loaded
print("Number of documents in corpus = ",len(corpus))

Number of documents in corpus =  746


In [ ]:
#corpus tupe
print(type(corpus))

<class 'list'>


In [ ]:
#printing first part of corpus
print(corpus[1])

not sure lost flat characters audience nearly half walked


In [ ]:
#fit function
def fit(dataset):
  storage_set = set()
  if isinstance(dataset,list):
    for document in dataset:
      for word in document.split(" "):
        storage_set.add(word)
  storage_set = sorted(list(storage_set))
  vocab = {j:i for i,j in enumerate(storage_set)}
  return vocab

vocab =  fit(corpus)
print(vocab)


{'aailiyah': 0, 'abandoned': 1, 'ability': 2, 'abroad': 3, 'absolutely': 4, 'abstruse': 5, 'abysmal': 6, 'academy': 7, 'accents': 8, 'accessible': 9, 'acclaimed': 10, 'accolades': 11, 'accurate': 12, 'accurately': 13, 'accused': 14, 'achievement': 15, 'achille': 16, 'ackerman': 17, 'act': 18, 'acted': 19, 'acting': 20, 'action': 21, 'actions': 22, 'actor': 23, 'actors': 24, 'actress': 25, 'actresses': 26, 'actually': 27, 'adams': 28, 'adaptation': 29, 'add': 30, 'added': 31, 'addition': 32, 'admins': 33, 'admiration': 34, 'admitted': 35, 'adorable': 36, 'adrift': 37, 'adventure': 38, 'advise': 39, 'aerial': 40, 'aesthetically': 41, 'affected': 42, 'affleck': 43, 'afraid': 44, 'africa': 45, 'afternoon': 46, 'age': 47, 'aged': 48, 'ages': 49, 'ago': 50, 'agree': 51, 'agreed': 52, 'aimless': 53, 'air': 54, 'aired': 55, 'akasha': 56, 'akin': 57, 'alert': 58, 'alexander': 59, 'alike': 60, 'allison': 61, 'allow': 62, 'allowing': 63, 'almost': 64, 'along': 65, 'alongside': 66, 'already': 67, 

In [ ]:
#transform function

def IDF(dataset,word):
  count = 0
  for row in dataset:
    if word in row:
      count = count+1
  return count


def transform(dataset,vocab):
    rows = []
    columns = []
    values = []
    if isinstance(dataset, (list,)):
        for idx, row in enumerate(tqdm(dataset)): # for each document in the dataset
            # it will return a dict type object where key is the word and values is its frequency, {word:frequency}
            word_freq = dict(Counter(row.split()))
            # for every unique word in the document
            for word, freq in word_freq.items():  # for each unique word in the review.                
                if len(word) < 2:
                    continue
                # we will check if its there in the vocabulary that we build in fit() function
                # dict.get() function will return the values, if the key doesn't exits it will return -1
                col_index = vocab.get(word, -1) # retreving the dimension number of a word
                # if the word exists
                if col_index !=-1:
                    # we are storing the index of the document
                    rows.append(idx)
                    # we are storing the dimensions of the word
                    columns.append(col_index)
                    # we are storing the frequency of the word

                    #  every thing here is same except
                    # (val = (freq/len(row.split()))*(log10(len(dataset)/IDF(dataset,word))))
                    
                    val = (freq/len(row.split()))*(log10(len(dataset)/IDF(dataset,word)))  
                    values.append(val) #val-freq
        return csr_matrix((values, (rows,columns)), shape=(len(dataset),len(vocab)))
    else:
        print("you need to pass list of strings")

In [ ]:
print(list(vocab.keys()))
print(transform(corpus, vocab).toarray())

  0%|          | 0/746 [00:00<?, ?it/s]

['aailiyah', 'abandoned', 'ability', 'abroad', 'absolutely', 'abstruse', 'abysmal', 'academy', 'accents', 'accessible', 'acclaimed', 'accolades', 'accurate', 'accurately', 'accused', 'achievement', 'achille', 'ackerman', 'act', 'acted', 'acting', 'action', 'actions', 'actor', 'actors', 'actress', 'actresses', 'actually', 'adams', 'adaptation', 'add', 'added', 'addition', 'admins', 'admiration', 'admitted', 'adorable', 'adrift', 'adventure', 'advise', 'aerial', 'aesthetically', 'affected', 'affleck', 'afraid', 'africa', 'afternoon', 'age', 'aged', 'ages', 'ago', 'agree', 'agreed', 'aimless', 'air', 'aired', 'akasha', 'akin', 'alert', 'alexander', 'alike', 'allison', 'allow', 'allowing', 'almost', 'along', 'alongside', 'already', 'also', 'although', 'always', 'amateurish', 'amaze', 'amazed', 'amazing', 'amazingly', 'america', 'american', 'americans', 'among', 'amount', 'amusing', 'amust', 'anatomist', 'angel', 'angela', 'angeles', 'angelina', 'angle', 'angles', 'angry', 'anguish', 'angus

100%|██████████| 746/746 [00:00<00:00, 1102.62it/s]

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
matrix_a=transform(corpus, vocab)
#print(matrix_a[0])
print("Shape of TF IDF Vector : "+str(transform(corpus, vocab).shape))
print(matrix_a)

100%|██████████| 746/746 [00:00<00:00, 1065.16it/s]


Shape of TF IDF Vector : (746, 2897)
  (0, 53)	0.3590923534340836
  (0, 689)	0.3590923534340836
  (0, 721)	0.3590923534340836
  (0, 1549)	0.14672110289208123
  (0, 1655)	0.08854824646102896
  (0, 1657)	0.26182344713612815
  (0, 2294)	0.2534550984323015
  (0, 2888)	0.27172110289208123
  (1, 149)	0.24152986923740552
  (1, 375)	0.153486348182044
  (1, 969)	0.28574542575652084
  (1, 1136)	0.22529342082871245
  (1, 1515)	0.25229764846052294
  (1, 1681)	0.3191932030525187
  (1, 1717)	0.0843106083517591
  (1, 2453)	0.24152986923740552
  (1, 2773)	0.28574542575652084
  (2, 20)	0.06745653791821944
  (2, 64)	0.10097349042280757
  (2, 89)	0.13535309641098356
  (2, 124)	0.15119678039329834
  (2, 145)	0.15119678039329834
  (2, 202)	0.13535309641098356
  (2, 237)	0.10097349042280757
  (2, 321)	0.09638663906918124
  :	:
  (741, 269)	0.3243826908778152
  (741, 430)	0.41039126106752405
  (741, 1100)	0.24665868454206155
  (741, 1358)	0.41039126106752405
  (741, 1426)	0.36738697597266967
  (741, 2478)	0.

In [ ]:
print(matrix_a[0].toarray())

[[0. 0. 0. ... 0. 0. 0.]]


In [ ]:
matrix_a

<746x2897 sparse matrix of type '<class 'numpy.float64'>'
	with 6964 stored elements in Compressed Sparse Row format>

##Compare to sklearn data


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer #this is instruction
vec = TfidfVectorizer()
vec.fit(corpus)
skl_output = vec.transform(corpus)
print(vec.idf_)
#print(skl_output.toarray())

[6.922918   6.922918   6.22977082 ... 6.922918   6.5174529  6.922918  ]


In [ ]:
print(skl_output[0])

  (0, 2878)	0.35781145622317734
  (0, 2287)	0.3377679916467555
  (0, 1653)	0.35781145622317734
  (0, 1651)	0.16192317905848022
  (0, 1545)	0.30566026894803877
  (0, 720)	0.4123943870778812
  (0, 688)	0.4123943870778812
  (0, 53)	0.4123943870778812


In [ ]:
print(skl_output[0].toarray())

[[0. 0. 0. ... 0. 0. 0.]]


In [ ]:
print(vec.get_feature_names())

['aailiyah', 'abandoned', 'ability', 'abroad', 'absolutely', 'abstruse', 'abysmal', 'academy', 'accents', 'accessible', 'acclaimed', 'accolades', 'accurate', 'accurately', 'accused', 'achievement', 'achille', 'ackerman', 'act', 'acted', 'acting', 'action', 'actions', 'actor', 'actors', 'actress', 'actresses', 'actually', 'adams', 'adaptation', 'add', 'added', 'addition', 'admins', 'admiration', 'admitted', 'adorable', 'adrift', 'adventure', 'advise', 'aerial', 'aesthetically', 'affected', 'affleck', 'afraid', 'africa', 'afternoon', 'age', 'aged', 'ages', 'ago', 'agree', 'agreed', 'aimless', 'air', 'aired', 'akasha', 'akin', 'alert', 'alexander', 'alike', 'allison', 'allow', 'allowing', 'almost', 'along', 'alongside', 'already', 'also', 'although', 'always', 'amateurish', 'amaze', 'amazed', 'amazing', 'amazingly', 'america', 'american', 'americans', 'among', 'amount', 'amusing', 'amust', 'anatomist', 'angel', 'angela', 'angeles', 'angelina', 'angle', 'angles', 'angry', 'anguish', 'angus

# Task 2
#### get top 50 values

* import libs
* fit
  * desending order (reffer:https://www.w3resource.com/python-exercises/dictionary/python-data-type-dictionary-exercise-1.php)
  * change[vocab = {j:i for i,j in enumerate(storage_set)}] to only give 50 thats 49 AKA "(storage_set[:50])"
    * print this shit [print('reverse of 50')]
* idf
* transform 
  * print this tramsform (AKA:sparce martix)
* normalize your sparse matrix using L2 normalization (reffer:https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html)



In [ ]:
# Function to calculate the no. of times a word appears in a whole dataset
def IDF(dataset,word):
  count = 0
  for row in dataset:
    if word in row:
      count = count+1
  return count


# Modifying FIT method for printing out words with top 100 IDF scores
# Input : set of documents ; Output: word, dimension number pair for each word
def fit(dataset):
  unique_words = [] 
  IDF_val = []
  for row in dataset:
    for word in row.split(" "):
      if len(word)>=2 and word not in unique_words:
        unique_words.append(word) # Add each unique word of length>2 to the list
  
  for word in unique_words:
    val = log10(len(dataset)/IDF(dataset,word))
    IDF_val.append(val) # Compute IDF scores for each word in list
    
  # Sort both lists w.r.t IDF scores
  for i in range(len(IDF_val)):
    for j in range(len(IDF_val)):
      if IDF_val[j] < IDF_val[i]:

        temp_a = IDF_val[j]
        IDF_val[j] = IDF_val[i]
        IDF_val[i] = temp_a
        
        temp_b = unique_words[j]
        unique_words[j] = unique_words[i]
        unique_words[i] = temp_b
        
  vocab_a = {j:i for i,j in enumerate(unique_words[:50])} # Enumerate the list, i.e., give consecutive numbers to each item, store in a dict
  return vocab_a

vocab_a = fit(corpus)
print(vocab_a)
#vocab_a

{'aimless': 0, 'distressed': 1, 'drifting': 2, 'nearly': 3, 'attempting': 4, 'artiness': 5, 'gerardo': 6, 'emptiness': 7, 'messages': 8, 'buffet': 9, 'science': 10, 'teacher': 11, 'owls': 12, 'florida': 13, 'muppets': 14, 'overdue': 15, 'screenplay': 16, 'post': 17, 'practically': 18, 'structure': 19, 'tightly': 20, 'constructed': 21, 'vitally': 22, 'occurs': 23, 'content': 24, 'dozen': 25, 'highest': 26, 'superlative': 27, 'require': 28, 'puzzle': 29, 'solving': 30, 'fit': 31, 'pulls': 32, 'punches': 33, 'graphics': 34, 'insane': 35, 'massive': 36, 'unlockable': 37, 'properly': 38, 'rocks': 39, 'doomed': 40, 'conception': 41, 'minor': 42, 'changing': 43, 'confirm': 44, 'generic': 45, 'managed': 46, 'exaggerating': 47, 'trailer': 48, 'carrell': 49}


In [ ]:
#transform function for task 2

def IDF(dataset,word):
  count = 0
  for row in dataset:
    if word in row:
      count = count+1
  return count


def transform(dataset,vocab):
    rows = []
    columns = []
    values = []
    if isinstance(dataset, (list,)):
        for idx, row in enumerate(tqdm(dataset)): # for each document in the dataset
            # it will return a dict type object where key is the word and values is its frequency, {word:frequency}
            word_freq = dict(Counter(row.split()))
            # for every unique word in the document
            for word, freq in word_freq.items():  # for each unique word in the review.                
                if len(word) < 2:
                    continue
                # we will check if its there in the vocabulary that we build in fit() function
                # dict.get() function will return the values, if the key doesn't exits it will return -1
                col_index = vocab.get(word, -1) # retreving the dimension number of a word
                # if the word exists
                if col_index !=-1:
                    # we are storing the index of the document
                    rows.append(idx)
                    # we are storing the dimensions of the word
                    columns.append(col_index)
                    # we are storing the frequency of the word

                    #  every thing here is same except
                    # (val = (freq/len(row.split()))*(log10(len(dataset)/IDF(dataset,word))))
                    
                    val = (freq/len(row.split()))*(log10(len(dataset)/IDF(dataset,word)))  
                    values.append(val) #val-freq
        return csr_matrix((values, (rows,columns)), shape=(len(dataset),len(vocab)))
    else:
        print("you need to pass list of strings")

In [ ]:
print(list(vocab_a.keys()))
print("Shape of TF IDF Vector : "+str(transform(corpus, vocab_a).shape))
#print(transform(corpus, vocab_a))
wasd = transform(corpus, vocab_a)
print(wasd)

100%|██████████| 746/746 [00:00<00:00, 53937.20it/s]

['aimless', 'distressed', 'drifting', 'nearly', 'attempting', 'artiness', 'gerardo', 'emptiness', 'messages', 'buffet', 'science', 'teacher', 'owls', 'florida', 'muppets', 'overdue', 'screenplay', 'post', 'practically', 'structure', 'tightly', 'constructed', 'vitally', 'occurs', 'content', 'dozen', 'highest', 'superlative', 'require', 'puzzle', 'solving', 'fit', 'pulls', 'punches', 'graphics', 'insane', 'massive', 'unlockable', 'properly', 'rocks', 'doomed', 'conception', 'minor', 'changing', 'confirm', 'generic', 'managed', 'exaggerating', 'trailer', 'carrell']
Shape of TF IDF Vector : (746, 50)
  (0, 0)	0.3590923534340836
  (0, 1)	0.3590923534340836
  (0, 2)	0.3590923534340836
  (1, 3)	0.3191932030525187
  (2, 4)	0.15119678039329834
  (2, 5)	0.15119678039329834
  (4, 6)	0.2872738827472669
  (5, 7)	0.2872738827472669
  (7, 8)	0.3191932030525187
  (9, 9)	0.47878980457877807
  (9, 10)	0.47878980457877807
  (9, 11)	0.47878980457877807
  (10, 12)	0.9575796091575561
  (11, 13)	0.3590923534

In [ ]:
wasd_normalized = normalize(wasd, norm='l2')
print(wasd_normalized)

  (0, 0)	0.5773502691896257
  (0, 1)	0.5773502691896257
  (0, 2)	0.5773502691896257
  (1, 3)	1.0
  (2, 4)	0.7071067811865475
  (2, 5)	0.7071067811865475
  (4, 6)	1.0
  (5, 7)	1.0
  (7, 8)	1.0
  (9, 9)	0.5773502691896257
  (9, 10)	0.5773502691896257
  (9, 11)	0.5773502691896257
  (10, 12)	1.0
  (11, 13)	1.0
  (12, 14)	1.0
  (16, 15)	1.0
  (17, 16)	0.7071067811865476
  (17, 17)	0.7071067811865476
  (18, 18)	1.0
  (19, 19)	0.1414213562373095
  (19, 20)	0.1414213562373095
  (19, 21)	0.1414213562373095
  (19, 22)	0.1414213562373095
  (19, 23)	0.1414213562373095
  (19, 24)	0.1414213562373095
  (19, 25)	0.1414213562373095
  (19, 26)	0.1414213562373095
  (19, 27)	0.1414213562373095
  (19, 28)	0.1414213562373095
  (19, 29)	0.1414213562373095
  (19, 30)	0.1414213562373095
  (19, 31)	0.282842712474619
  (19, 32)	0.1414213562373095
  (19, 33)	0.1414213562373095
  (19, 34)	0.4242640687119285
  (19, 35)	0.1414213562373095
  (19, 36)	0.4242640687119285
  (19, 37)	0.1414213562373095
  (19, 38)	0.14142

In [ ]:
print("sparce")
print(wasd)
zxc = wasd.todense
print("dence")
print(zxc)
print("dence shape")
#print(aaa.shape)

sparce
  (0, 0)	0.3590923534340836
  (0, 1)	0.3590923534340836
  (0, 2)	0.3590923534340836
  (1, 3)	0.3191932030525187
  (2, 4)	0.15119678039329834
  (2, 5)	0.15119678039329834
  (4, 6)	0.2872738827472669
  (5, 7)	0.2872738827472669
  (7, 8)	0.3191932030525187
  (9, 9)	0.47878980457877807
  (9, 10)	0.47878980457877807
  (9, 11)	0.47878980457877807
  (10, 12)	0.9575796091575561
  (11, 13)	0.3590923534340836
  (12, 14)	0.7181847068681672
  (16, 15)	0.2209799098055899
  (17, 16)	0.20519563053376202
  (17, 17)	0.20519563053376202
  (18, 18)	0.41039126106752405
  (19, 19)	0.006543824208365988
  (19, 20)	0.006543824208365988
  (19, 21)	0.006543824208365988
  (19, 22)	0.006543824208365988
  (19, 23)	0.006543824208365988
  (19, 24)	0.006543824208365988
  (19, 25)	0.006543824208365988
  (19, 26)	0.006543824208365988
  (19, 27)	0.006543824208365988
  (19, 28)	0.006543824208365988
  (19, 29)	0.006543824208365988
  (19, 30)	0.006543824208365988
  (19, 31)	0.013087648416731976
  (19, 32)	0.00654382

In [ ]:
print(zxc)

<bound method spmatrix.todense of <746x50 sparse matrix of type '<class 'numpy.float64'>'
	with 50 stored elements in Compressed Sparse Row format>>
